### ISSUE TITLE
Getting failed to download

### ISSUE THREAD

**Issue by azahinhasan** [lachiejames/npm-downloads-increaser#100]
Getting this error. 
![image](https://user-images.githubusercontent.com/29199730/198686601-ec9d9e1c-5f0c-4903-a22a-362b6a2de874.png)

But the package is active: https://www.npmjs.com/package/@azahinhasan/age-calculator

**Comment by hryhorii515** [comment]
Hi @lachiejames Is this package still available? I'm getting the same error above.
```
Error: Failed to download https://api.npms.io/v2/package/%40azahinhasan%2Fage-calculator
```
