### ISSUE TITLE
Doesn’t work….

### ISSUE THREAD

**Issue by HisRoyalBaguettes** [lachiejames/npm-downloads-increaser#46]
Doesn’t work. Tried using it, doesn't update the package weekly downloads.

**Comment by lachiejames** [comment]
Hey @HisRoyalBaguettes,

The weekly downloads are updated **once every 24 hours** on npmJS.  Has it been 24 hours since you ran the code?

If not, please try checking again tomorrow and let me know if the download count has changed.  I will add this information to the README.

**Comment by HisRoyalBaguettes** [comment]
works, thanks. I showed off my friends about this npm package, also told em to use it for testing only, thanks.
