### ISSUE TITLE
how can use it with package that contain a namespace like "@babel/core" ?

### ISSUE THREAD

**Issue by pinmosarn** [lachiejames/npm-downloads-increaser#91]
what I tried this package on a package with a namespace such "@babel/core" package I got this error.
```
× Error: Failed to download https://api.npms.io/v2/package/@bable/core
Request failed with status code 404
```
I also tried it with change slash character to %2F "@babel%2Fcore" but nothing happened.

please try your self and you will no what i am talking about.

**Comment by lachiejamesCTC** [comment]
Hey @pinmosarn apologies for the late reply.  I have fixed this in https://github.com/lachiejames/npm-downloads-increaser/pull/93

<img width="926" alt="image" src="https://user-images.githubusercontent.com/103395442/166518697-de034b20-0050-4b26-9ee4-91b616783ca8.png">
